# Generated by Django 5.0.7 on 2025-03-16 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='AvisRecrutement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0, verbose_name='N°')),
                ('intitule', models.TextField(default='', verbose_name="INTITULÉ DE L'AVIS")),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('date_exp', models.DateTimeField()),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('is_answered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('date_exp', models.DateField()),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('mot_de_pass', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_activite', models.CharField(max_length=100)),
                ('informatique', models.BooleanField(default=False)),
                ('tablettes', models.BooleanField(default=False)),
                ('enquete', models.BooleanField(default=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('situation_matrimoniale', models.CharField(choices=[('célibataire', 'Célibataire'), ('marié(e)', 'Marié(e)'), ('divorcé(e)', 'Divorcé(e)'), ('veuf(ve)', 'Veuf(ve)')], max_length=50)),
                ('telephone_contact', models.CharField(max_length=20)),
                ('telephone_whatsapp', models.CharField(max_length=20)),
                ('numero_identification', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.FileField(upload_to='cv/')),
                ('certificat_nationalite', models.FileField(upload_to='cv/')),
                ('lettre_motivation', models.FileField(upload_to='cv/')),
                ('copie_legalise_bac', models.FileField(upload_to='cv/')),
                ('copie_extrait_naissance', models.FileField(upload_to='cv/')),
                ('certificat_domicile_ou_residence', models.FileField(upload_to='cv/')),
                ('atestation_enquete', models.FileField(upload_to='cv/')),
                ('dernier_diplome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plateforme.diplome')),
                ('langue_parlee1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='langue_parlee1', to='plateforme.langue')),
                ('langue_parlee2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='langue_parlee2', to='plateforme.langue')),
                ('langue_parlee3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='langue_parlee3', to='plateforme.langue')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plateforme.region')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatureOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_candidature', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('ACCEPTE', 'Accepté'), ('REJETE', 'Rejeté')], max_length=50)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='plateforme.candidat')),
                ('offre_emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='plateforme.offreemploi')),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_postulation', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plateforme.candidat')),
                ('offre_emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plateforme.offreemploi')),
            ],
        ),
    ]
